kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: 10.245.0.0/16
  serviceSubnet: 10.97.0.0/16
  ipFamily: ipv4
nodes:
- role: control-plane
  image: kindest/node:v1.35.0
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6444
    protocol: TCP
- role: worker
  image: kindest/node:v1.35.0
  extraPortMappings:
  - containerPort: 8222
    hostPort: 9223
    protocol: TCP
